version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
      - type: volume
        source: node_modules_volume
        target: /api/node_modules
    command: npm run start:dev
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./src/infrastructure/database/init
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: db-store
        target: /var/lib/postgresql/data
volumes:
  node_modules_volume:
  db-store: